### ISSUE TITLE
The OfferAccepted and OfferDeclined events are missing the Offer unique identifier

### ISSUE THREAD

**Issue by moonrockfamily** [ocas/DomesticOnDemand#3]
### Context

- [ ] An _education institution_ creates an Offer.
- [ ] An [Offer](https://github.com/ocas/domesticondemand/wiki/offer) has a globally unique identifier (GUID).
- [ ] An Offer identifies a single Program Intake.
- [ ] An Offer is **NOT** required to identify an Application Program Choice.
- [ ] An _applicant_ may accept an Offer.
- [ ] An _applicant_ may decline an Offer.
- [ ] An _education institution_ may create one or more Offers for each Application

### Supporting Context
- [ ] An _education institution_ creates a Program Intake.
- [ ] A Program Intake has a globally unique identifier (GUID).
- [ ] An _applicant_ creates an [Application Program Choice](https://github.com/ocas/domesticondemand/wiki/ProgramChoice).
- [ ] An [Application Program Choice](https://github.com/ocas/domesticondemand/wiki/ProgramChoice) has a globally unique identifier (GUID)
- [ ] An Application Program Choice identifies a single Program Intake.

### Issue

- [ ] 	The OfferAccepted and OfferDeclined [events](https://github.com/ocas/domesticondemand/wiki/Events) are missing the Offer unique identifier as per the [Offer model](https://github.com/ocas/domesticondemand/wiki/offer)

**Comment by ben-harper** [comment]
This has been addressed in the updated models
