### ISSUE TITLE
The Program Choice and Offer models are missing a Program Intake unique identifier

### ISSUE THREAD

**Issue by moonrockfamily** [ocas/DomesticOnDemand#4]
### Context
- [ ] An _education institution_ creates a Program Intake.
- [ ] A Program Intake has an institution unique identifier/GUID.
- [ ] An _applicant_ creates an [Application Program Choice](https://github.com/ocas/domesticondemand/wiki/ProgramChoice).
- [ ] An [Application Program Choice](https://github.com/ocas/domesticondemand/wiki/ProgramChoice) has a globally unique identifier (GUID)
- [ ] An Application Program Choice identifies a single Program Intake.
- [ ] An Offer identifies a single Program Intake.

**Comment by ben-harper** [comment]
Presently in our domestic Apply solution's program catalogue we don't capture the College's unique identifier for the intake.  I do think it makes sense to have a unique identifier of the intake in the Program Choice, at present it would not be clear what we would transmit in that value at this time.
We could
1) send the globally unique identifier OCAS has assigned for the intake in the Domestic Program Catalogue.  This is not likely to be of utility to the college as that identifier is not already shared back to colleges
2) add the attribute to the model however leave it optional/null until such time as the Domestic Program Catalogue is updated to capture the College's identifier (note that this identifier would not be guaranteed globally unique, but I believe that is to be expected)

Additional context for this: OCAS is developing a more flexible Offerings Catalogue that would be a single place to manage all 
 Colleges' offerings shared with OCAS (Programs, courses, FT/PT, Int'l/Domestic),  This system will capture the intake's unique identifier from the college similar to what is done in International.  This new Catalogue will not be developed in time for the Domestic On Demand launch.

**Comment by moonrockfamily** [comment]
### A single `id` could work!

The concept of ownership/authorship coupled with the necessity to opaquely identify entities will facilitate varying identification schemes without adding new communication elements.  

#### Prime Rule

- [ ] an entity must have an opaque unique identifier within the scope of the authoring system

#### Domain

- [ ] an Offer is _authored by_ the **education institution** (https://github.com/ocas/domesticondemand/wiki/offers-endpoint)
- [ ] a Program Choice is _authored by_ the **education institution**
- [ ] an Application is _authored by_ the **OCAS Application system** on behalf of the student.

#### Required Policy

- [ ] an entity must have a unique identifier as assigned by the author
- [ ] an entity must have an author
- [ ] all communication of entity identification _should_ use its unique identifier

### Unidentified Flying Entities

You raise an excellent challenge for legacy systems that do not communicate opaque unique identifier representations of the entities they share.  For these it would seem reasonable they continue to aggregate the attributes of the entity needed for uniqueness in their system.  At such time when no participating system requires the superfluous attributes they may be dropped from the communication in favor of the simpler/concise unique identifier.  

#### OCAS Application system - Legacy Identification Handling Policy
- [ ] when the system accepts an entity without a unique identifier it will assign a unique identifier; take ownership!
- [ ] when the system receives a communication without an entity unique identifier, it will use the provided entity attributes to identify the entity
- [ ] when the system communicates an entity identifier it will always provide the opaque unique identifier **AND the unique key attributes**

**Comment by moonrockfamily** [comment]
### Lenient consumption

The _system_ will accept varying entity identification schemes.  When both are provided, the Unique Id will be preferred.
1 - Unique Id 
2 - Composite key values


### Strict production

The _system_ will produce messages with strict adherence to entity identification schemes.  This will permit consumers the flexibility to choose the values most suited to their operation.
Entity identification will be communicated via both:
1 - Unique Id 
2 - Composite key values

**Comment by moonrockfamily** [comment]
oops.  Meant to copy the content to a discussion NOT close the issue!
